name: CI

on:
  pull_request:
  # Enable running CI from the GitHub GUI (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nox
        uses: wntrblm/nox@2024.03.02
        with:
          python-versions: "3.9, 3.10"
      - name: Install wxPython dependencies
        # See https://github.com/wxWidgets/Phoenix#prerequisites for more info
        run: |
          sudo apt-get install dpkg-dev build-essential python3-dev freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libjpeg-dev libnotify-dev libpng-dev libsdl2-dev libsm-dev libtiff-dev libwebkit2gtk-4.0-dev libxtst-dev
      - name: Run tests
        run: nox -s tests --verbose
            
        
